/**
 * Generated by "@vuepress/internal-site-data"
 */
export const siteData = {
  "title": "",
  "description": "",
  "base": "/",
  "headTags": [],
  "pages": [
    {
      "title": "Home",
      "frontmatter": {
        "home": true,
        "heroText": "OvO",
        "tagline": "简洁而快速的UI框架",
        "actionText": "快速上手 →",
        "actionLink": "/zh/guide/",
        "features": [
          {
            "title": "简洁至上",
            "details": "以组件为中心,每个组件精心打磨,专业的UI设计让每个组件简约大气。"
          },
          {
            "title": "uni-app驱动",
            "details": "享受uni-app带来的跨越全端的快感。"
          },
          {
            "title": "高性能",
            "details": "使用nvue图层渲染,使得整个页面无比丝滑。"
          }
        ],
        "footer": "MIT Licensed | Copyright © 2020-present JackCc AF"
      },
      "regularPath": "/",
      "relativePath": "README.md",
      "key": "v-0fa1d1b0",
      "path": "/"
    }
  ],
  "themeConfig": {
    "logo": "/assets/img/logo.png",
    "nav": [
      {
        "text": "主页",
        "link": "/"
      },
      {
        "text": "文档",
        "link": "/guide/"
      },
      {
        "text": "分享",
        "link": "https://google.com"
      },
      {
        "text": "选择语言",
        "ariaLabel": "Language Menu",
        "items": [
          {
            "text": "Chinese",
            "link": "/language/chinese/"
          },
          {
            "text": "Japanese",
            "link": "/language/japanese/"
          }
        ]
      }
    ]
  }
}